import Foundation

public enum SpeechLanguage : String {
    case unknown = ""
    case Arabic = "ar-SA"
    case Chinese = "zh-CN"
    case ChineseHongKong = "zh-HK"
    case ChineseTaiwan = "zh-TW"
    case Czech = "cs-CZ"
    case Danish = "de-DK"
    case Dutch = "nl-NL"
    case DutchBelgium = "nl-BE"
    case English = "en-US"
    case EnglishUK = "en-UK"
    case EnglishAustralia = "en-AU"
    case EnglishIreland = "en-IE"
    case EnglishSouthAfrica = "en-ZA"
    case Finnish = "fi-FI"
    case French = "fr-FR"
    case FrenchCanada = "fr-CA"
    case German = "de-DE"
    case Greek = "el-GR"
    case Hebrew = "he-IL"
    case Hindi = "hi-IN"
    case Hungarian = "hu-HU"
    case Indonesian = "id-ID"
    case Italian = "it-IT"
    case Japanese = "ja-JP"
    case Korean = "ko-KR"
    case Norwegian = "no-NO"
    case Polish = "pl-PL"
    case Portuguese = "pt-PT"
    case PortugueseBrazil = "pt-BR"
    case Romanian = "ro-RO"
    case Russian = "ru-RU"
    case Slovak = "sk-SK"
    case Spanish = "es-ES"
    case SpanishMexico = "es-MX"
    case Swedish = "sv-SE"
    case Thai = "th-TH"
    case Turkish = "tr-TR"
}
